In [59]:
import numpy as np
import pandas as pd

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

sola_remix = ['real', 'muerte', 'real', 'muerte', 'real', 'angel', 'sola', 'sola', 'sola']
amanece = ['real', 'muerte', 'real', 'muerte', 'real', 'muerte', 'casualidad', 'sucede', 'ganas', 'ganas', 'ganas']
secreto = ['real', 'muerte', 'real', 'muerte', 'real', 'muerte', 'secreto', 'secreto', 'secreto', 'secreto']

lyrics = [' '.join(sola_remix), ' '.join(amanece), ' '.join(secreto)]

vectorizer = CountVectorizer()

frequency = vectorizer.fit_transform(lyrics).toarray()

In [61]:
pd.DataFrame(frequency, columns=vectorizer.get_feature_names_out())

frequency

array([[1, 0, 0, 2, 3, 0, 3, 0],
       [0, 1, 3, 3, 3, 0, 0, 1],
       [0, 0, 0, 3, 3, 4, 0, 0]])

In [62]:
N = frequency.shape[0]

# Term Frequency    
tf = frequency / np.sum(frequency, axis=1, keepdims=True)

# Document Frequency
df = np.sum(frequency > 0, axis=0)

# Inverse Document Frequency
idf = np.log(N / (df + 1))

# TF-IDF
tf_idf = tf * idf

pd.DataFrame(tf_idf, columns=vectorizer.get_feature_names_out())

,angel,casualidad,ganas,muerte,real,secreto,sola,sucede
0,0.045052,0.00000,0.000000,-0.063929,-0.095894,0.000000,0.135155,0.00000
1,0.000000,0.03686,0.110581,-0.078459,-0.078459,0.000000,0.000000,0.03686
2,0.000000,0.00000,0.000000,-0.086305,-0.086305,0.162186,0.000000,0.00000

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf = tfidf_vectorizer.fit_transform(lyrics).toarray()
pd.DataFrame(tfidf, columns=tfidf_vectorizer.get_feature_names_out())

,angel,casualidad,ganas,muerte,real,secreto,sola,sucede
0,0.262299,0.00000,0.000000,0.309836,0.464754,0.000000,0.786896,0.00000
1,0.000000,0.24057,0.721711,0.426254,0.426254,0.000000,0.000000,0.24057
2,0.000000,0.00000,0.000000,0.375387,0.375387,0.847448,0.000000,0.00000