In [55]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [56]:
data = pd.read_parquet("urbania_cleaned_20250921_191417.parquet")
data

,index,global_index,scraped_at,title,url,location,has_location,district,property_type,price_raw,price_numeric,currency,has_price,price_per_sqm,area_raw,area_numeric,bedrooms,bathrooms,has_parking,parking_count,has_pool,has_garden,has_balcony,has_elevator,has_security,has_gym,is_furnished,allows_pets,is_new,has_terrace,has_laundry,has_air_conditioning,image_count,image_urls,page,site_page,element_class,element_tag,data_completeness,feature_count,full_text
0,4,3,2025-09-20T18:59:45.915152,Entrega inmediata · Entrega inmediata,N/A,Miraflores,True,None,apartment,"S/ 2,909",2909.0,PEN,True,48.483333,53 a 60 m² tot.,60,2.0,NaN,False,0,True,True,False,False,False,True,True,False,True,False,False,False,0,[],1,1,postingsList-module__card-container,div,58.333333,5,Entrega inmediata · Entrega inmediata\n1 Mes R...
1,5,4,2025-09-20T18:59:45.926426,S/ 300 Mantenimiento,N/A,Surquillo,True,None,apartment,"S/ 2,450",2450.0,PEN,True,40.163934,61 m² tot.,61,2.0,2.0,False,0,False,False,True,True,True,False,True,False,False,False,False,False,0,[],1,1,postingsList-module__card-container,div,58.333333,4,"Seguridad\n22\nS/ 2,450\nS/ 300 Mantenimiento\..."
2,6,5,2025-09-20T18:59:45.937012,"S/ 3,200 · USD 900",N/A,Miraflores,True,None,property,"S/ 3,200 · USD 900",3200.0,PEN,True,32.653061,98 m² tot.,98,NaN,NaN,False,0,False,False,False,False,False,False,False,False,False,False,False,False,0,[],1,1,postingsList-module__card-container,div,29.166667,0,"18\nS/ 3,200 · USD 900\nS/ 170 Mantenimiento\n..."
3,7,6,2025-09-20T18:59:45.949084,Guardianía/Seguridad privada,N/A,Miraflores,True,None,house,"S/ 2,664 · USD 750",2664.0,PEN,True,44.400000,60 m² tot.,60,1.0,1.0,False,0,False,False,False,True,True,False,True,False,False,False,True,False,0,[],1,1,postingsList-module__card-container,div,58.333333,4,"Guardianía/Seguridad privada\n11\nS/ 2,664 · U..."
4,8,7,2025-09-20T18:59:45.963256,"S/ 5,000 · USD 1,428",N/A,Miraflores,True,None,apartment,"S/ 5,000 · USD 1,428",5000.0,PEN,True,55.555556,90 m² tot.,90,2.0,2.0,True,1,False,False,False,False,True,False,True,False,True,False,True,False,0,[],1,1,postingsList-module__card-container,div,66.666667,5,"Seguridad\n24\nS/ 5,000 · USD 1,428\nS/ 580 Ma..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329,22,1491,2025-09-20T19:07:47.897617,"S/ 2,270 · USD 650",N/A,Miraflores,True,None,apartment,"S/ 2,270 · USD 650",2270.0,PEN,True,48.297872,47 m² tot.,47,1.0,1.0,False,0,False,False,False,True,True,False,True,False,False,False,False,False,0,[],50,50,postingsList-module__card-container,div,54.166667,3,"Ascensor\n12\nS/ 2,270 · USD 650\nS/ 155 Mante..."
1330,23,1492,2025-09-20T19:07:47.908385,"S/ 12,390 · USD 3,500",N/A,San Isidro,True,None,property,"S/ 12,390 · USD 3,500",12390.0,PEN,True,38.718750,320 m² tot.,320,4.0,3.0,True,3,True,False,False,False,True,True,True,False,False,True,False,False,0,[],50,50,postingsList-module__card-container,div,70.833333,6,"Gimnasio\n12\nS/ 12,390 · USD 3,500\nS/ 1,200 ..."
1331,24,1493,2025-09-20T19:07:47.918931,"S/ 3,520 · USD 1,000",N/A,San Isidro,True,None,apartment,"S/ 3,520 · USD 1,000",3520.0,PEN,True,73.333333,48 m² tot.,48,1.0,1.0,False,0,False,False,False,False,True,False,True,False,False,False,False,False,0,[],50,50,postingsList-module__card-container,div,50.000000,2,"Amoblado\n14\nS/ 3,520 · USD 1,000\nS/ 250 Man..."
1332,25,1494,2025-09-20T19:07:47.929121,"S/ 14,060 · USD 850,000",N/A,Miraflores,True,None,apartment,"S/ 14,060 · USD 850,000",14060.0,PEN,True,39.717514,354 m² tot.,354,3.0,4.0,True,3,True,False,False,True,True,False,False,True,False,True,True,True,0,[],50,50,postingsList-module__card-container,div,79.166667,8,"Piscina\n19\nS/ 14,060 · USD 850,000\nS/ 1,481..."
1333,26,1495,2025-09-20T19:07:47.939292,Área de lavandería,N/A,Barranco,True,None,apartment,S/ 1900,1900.0,PEN,True,38.775510,49 m² tot.,49,1.0,1.0,True,1,False,False,False,False,False,False,False,False,False,True,True,False,0,[],50,50,postingsList-module__card-container,div,58.333333,3,"Área de lavandería\n22\nS/ 1,900\nS/ 300 Mante..."

In [57]:
data[data["location"] == 'Jesús María']["price_numeric"].max()
data["price_numeric"].max()

np.float64(74100.0)

In [58]:
data["price_numeric"].sort_values(ascending=False).head(10)

866     74100.0
583     42000.0
702     42000.0
142     38500.0
1019    38000.0
791     28704.0
461     28704.0
1152    28000.0
1046    28000.0
149     27600.0
Name: price_numeric, dtype: float64

In [59]:
data[data["price_numeric"] == 38500.0 ]["full_text"].iloc[0]

'Ascensor\n45\nS/ 38,500 · USD 9,900\nS/ 800 Mantenimiento\nCalle Domingo Orue 120 Miraflores\nBarboncito, Miraflores\n290 m² tot.\n4 dorm.\n3 baños\n2 estac.\nPent-house Duplex de Lujo con Jacuzzi privado. Miraflores Lima Perú, ubicado en la exclusiva zona de la Huaca Pucllana. Espectacular propiedad con Piscina/Jacuzzi privado, Parrilla, terraza vista panorámicas a la Huaca Pucllana, cerca de Ovalo de Miraflores Parque Kennedy y San Isidro, rodeado de los mejores restaurantes! Ubicado en un Edificio histórico completamente renovado con muebles de estreno, tiene 4 Dormitorios, 3. 5 baños, Sala con chimenea, Comedor para 10 personas! Bar! Cocina equipada, lavandería, Internet de 600mbps, Aire Acondicionado y mas! Pent-house, ubicado en los 2 últimos pisos del Edificio tiene 280 m2 ( 3, 000 Ft) Disfruta de una propiedad única, muy privada, con una arquitectura exquisita, amoblamiento de la mas alta calidad y altos estándares hoteleros. Primera Planta: Ingreso por ascensor al hall. Sala con Chimenea en piedra. Comedor para 10 personas. Bar. Lujoso baño de visita. Pasadizo Hall hacia para los dormitorios. Dormitorio 1 - Cama King /Tv con G00gle tv - baño privado Tina. Dormitorio 2- Cama Queen / Tv con G00gle tv baño compartido Ducha. Dorm 3 - 2 Camas singles / Tv con G00gle tv baño compartido Ducha. Cocina completamente equipada hasta para 12 personas. Escaleras hacia el segundo. **Todos los ambientes tienen Aire acondicionado y calefacción. Segunda Planta. Terraza con Parrilla (bbq) Mesa Terraza para 10 personas. Barra con grifo para preparar alimentos. Baño completo con ducha. Piscina/ Jacuzzi. Cuarto pequeño de Lavanderia. Dormitorio 4 - Cama de 1. 5 plazas. Escalera Caracol al mirador. 2 Estacionamientos disponibles. *Todos los dormitorios tienen sabanas blancas de algodon puro, toallas Premium. * Este Penthouse ha sido completamente remodelado el año 2024. * El Jacuzzi tiene capacidad para 4 personas en simultaneo. 2 Estacionamientos de 4 metros altura. Ultra Luxury Penthouse 2 stories in the heart of Miraflores, Lima Peru, historic building, Private Pool & Terrace with bbq Panoramic seaview, Facing Huaca Pucllana, walking distance to Ovalo Gutierrez, Parque Kennedy and Miguel Dasso, San Isidro, High-Speed Internet - 600 Mbps. All renewed with brand new furniture, Over 2, 700 ft² just for you. 4 Bedrooms with 3. 5 Ba, Fully equipped kitchen, living room, Dinning room for 10! Ac/ Heating. Washer/Dryer in unit. Free parking available. Pent-house, ubicado en los 2 últimos pisos del Edificio tiene 280 m2 ( 2, 950 Ft) Disfruta de una propiedad única, muy privada, con una arquitectura exquisita, amoblamiento de la mas alta calidad y altos estándares hoteleros. Primera Planta: Ingreso por ascensor al hall. Sala con Chimenea en piedra. Comedor para 10 personas. Bar. Lujoso baño de visita. Pasadizo Hall hacia los dormitorios. Dormitorio 1 - Cama King /Tv con G00gle tv - baño privado Tina. Dormitorio 2- Cama Queen / Tv con G00gle tv baño compartido Ducha. Dorm 3 - 2 Camas singles / Tv con G00gle tv baño compartido Ducha. Cocina completamente equipada hasta para 12 personas. Escaleras hacia el segundo. **Todos los ambientes tienen Aire acondicionado y calefacción. Segunda Planta. Terraza con Parrilla (bbq) Mesa Terraza para 10 personas. Barra con grifo para preparar alimentos. Baño completo con ducha. Piscina/ Jacuzzi. Cuarto pequeño de Lavanderia. Dormitorio 4 - Cama de 1. 5 plazas. Escalera Caracol al mirador. 2 Estacionamientos disponibles. *Todos los dormitorios tienen sabanas blancas de algodon puro, toallas Premium.\nSuper destacado\nWhatsApp\nContactar'

In [60]:
data = data[~(data["price_numeric"].isna())| ~(data["area_numeric"].isna())]
y = data["price_numeric"]
x = data["area_numeric"]

In [61]:
import gurobipy as gp

In [62]:
# Model

model = gp.Model("linear_regression")

# Decision variables 

b0 = model.addVar(lb=-gp.GRB.INFINITY, name="b0")
b1 = model.addVar(lb=-gp.GRB.INFINITY, name="b1")

# Objective function

errors = []

for i in range(len(x)):
    squared_error = (y[i] - (b0 + b1 * x[i]))**2
    errors.append(squared_error)

model.setObjective(gp.quicksum(errors), sense=gp.GRB.MINIMIZE)

# Optimize the model

model.optimize()

Gurobi Optimizer version 13.0.2 build v13.0.2rc1 (win64 - Windows 11+.0 (26200.2))

CPU model: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 0 rows, 2 columns and 0 nonzeros (Min)
Model fingerprint: 0x3679c20f
Model has 2 linear objective coefficients and an objective constant of 50326947491.05
Model has 3 quadratic objective terms
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [1e+07, 2e+09]
  QObjective range [3e+03, 5e+07]
  Bounds range     [0e+00, 0e+00]
  RHS range        [0e+00, 0e+00]
Warning: Model contains large objective coefficients
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.

Presolve time: 0.02s
Presolved: 0 rows, 2 columns, 0 nonzeros
Presolved model has 3 quadratic objective terms
Ordering time: 0.00s

Barrier statistics:
 Free vars  : 3
 AA' NZ     : 0.000e+00
 Factor NZ  : 1.000e+00
 Factor Ops : 1.000e+00 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0   5.03269475e+10  5.03269475e+10  0.00e+00 1.40e+04  0.00e+00     0s
   1   4.67179428e+10  5.02321013e+10  1.41e-08 1.33e+04  0.00e+00     0s
   2   4.24458324e+10  4.98431851e+10  3.01e-08 1.24e+04  0.00e+00     0s
   3   2.34652421e+10  4.15415494e+10  5.34e-08 7.08e+03  0.00e+00     0s
   4   1.58568848e+10  2.81110254e+10  4.12e-08 3.02e+03  0.00e+00     0s
   5   1.53976137e+10  2.62776692e+10  8.46e-08 2.58e+03  0.00e+00     0s
   6   1.41670611e+10  1.41670745e+10  1.01e-07 2.58e-03  0.00e+00     0s
   7   1.41670611e+10  1.41670611e+10  0.00e+00 2.58e-09  0.00e+00     0s

Barrier solved model in 7 iterations and 0.06 seconds (0.00 work units)
Optimal objective 1.41670611e+10

In [63]:
b0.x, b1.x

(-91.1671912150007, 40.06355672551716)

In [64]:
prediction = lambda x: b0.x + b1.x * x
prediction(40)

1511.3750778056858

In [65]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x.values.reshape(-1, 1), y.values)
model.intercept_, model.coef_[0]

(np.float64(-91.1671912150814), np.float64(40.063556725524954))

In [66]:
data[["area_numeric","bedrooms","bathrooms","price_numeric"]].corr()

               area_numeric  bedrooms  bathrooms  price_numeric
area_numeric       1.000000  0.630723   0.686655       0.687778
bedrooms           0.630723  1.000000   0.713723       0.400631
bathrooms          0.686655  0.713723   1.000000       0.492516
price_numeric      0.687778  0.400631   0.492516       1.000000

In [67]:
import upc_datasets

data = upc_datasets.load_dataset("pachamix_audio_core", download = True)

In [68]:
cols = [i for i in data.columns if i not in ["track_id",'title','genre_top',"artist_name"]]
data.select(cols)

shape: (106_574, 518)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ chroma_ce ┆ chroma_ce ┆ chroma_ce ┆ chroma_ce ┆ … ┆ zcr_media ┆ zcr_min_0 ┆ zcr_skew_ ┆ zcr_std_ │
│ ns_kurtos ┆ ns_kurtos ┆ ns_kurtos ┆ ns_kurtos ┆   ┆ n_01      ┆ 1         ┆ 01        ┆ 01       │
│ is_01     ┆ is_02     ┆ is_03     ┆ is_04     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7.180653  ┆ 5.230309  ┆ 0.249321  ┆ 1.34762   ┆ … ┆ 0.071289  ┆ 0.0       ┆ 2.089872  ┆ 0.061448 │
│ 1.888963  ┆ 0.760539  ┆ 0.345297  ┆ 2.295201  ┆ … ┆ 0.063965  ┆ 0.0       ┆ 1.716724  ┆ 0.06933  │
│ 0.527563  ┆ -0.077654 ┆ -0.27961  ┆ 0.685883  ┆ … ┆ 0.041504  ┆ 0.0       ┆ 2.193303  ┆ 0.044861 │
│ 3.702245  ┆ -0.291193 ┆ 2.196742  ┆ -0.234449 ┆ … ┆ 0.071777  ┆ 0.0       ┆ 3.542325  ┆ 0.0408   │
│ -0.193837 ┆ -0.198527 ┆ 0.201546  ┆ 0.258556  ┆ … ┆ 0.040039  ┆ 0.000977  ┆ 3.189831  ┆ 0.030993 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ -0.490129 ┆ 0.463834  ┆ 2.32197   ┆ -0.084352 ┆ … ┆ 0.02832   ┆ 0.003906  ┆ 0.955388  ┆ 0.012385 │
│ -0.461559 ┆ -0.229601 ┆ -0.496632 ┆ -0.422033 ┆ … ┆ 0.027832  ┆ 0.002441  ┆ 1.28306   ┆ 0.019059 │
│ 0.552473  ┆ -0.110498 ┆ -0.532014 ┆ 0.263131  ┆ … ┆ 0.037109  ┆ 0.003418  ┆ 0.828569  ┆ 0.017904 │
│ -0.176901 ┆ 0.187208  ┆ -0.050664 ┆ 0.368843  ┆ … ┆ 0.038086  ┆ 0.004883  ┆ 1.81874   ┆ 0.020133 │
│ 0.489665  ┆ 1.862421  ┆ 0.854461  ┆ -0.103666 ┆ … ┆ 0.044434  ┆ 0.004395  ┆ 4.687204  ┆ 0.137205 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [72]:
# Standard scaler
value_mean = data.select("chroma_cens_kurtosis_01").mean().item()
value_std = data.select("chroma_cens_kurtosis_01").std().item()


new_distribution = (data.select("chroma_cens_kurtosis_01") - value_mean )/ value_std

new_distribution.mean()
new_distribution.std()

shape: (1, 1)
┌─────────────────────────┐
│ chroma_cens_kurtosis_01 │
│ ---                     │
│ f64                     │
╞═════════════════════════╡
│ 1.0                     │
└─────────────────────────┘

In [73]:
# Min Max scaler

value_min = data.select("chroma_cens_kurtosis_01").min().item()
value_max = data.select("chroma_cens_kurtosis_01").max().item()

new_distribution = (data.select("chroma_cens_kurtosis_01") - value_min )/ (value_max - value_min)
print(new_distribution.min())
print(new_distribution.max())

shape: (1, 1)
┌─────────────────────────┐
│ chroma_cens_kurtosis_01 │
│ ---                     │
│ f64                     │
╞═════════════════════════╡
│ 0.0                     │
└─────────────────────────┘
shape: (1, 1)
┌─────────────────────────┐
│ chroma_cens_kurtosis_01 │
│ ---                     │
│ f64                     │
╞═════════════════════════╡
│ 1.0                     │
└─────────────────────────┘

In [74]:
# SKLEARN

from sklearn.preprocessing import StandardScaler, MinMaxScaler  


standard_scaler = StandardScaler()
min_max_scaler = MinMaxScaler()

standard_scaled_vars = standard_scaler.fit_transform(data.select(cols))
minmax_scaled_vars = min_max_scaler.fit_transform(data.select(cols))

In [75]:
# PCA

from sklearn.decomposition import PCA

pca = PCA(10)

reduced_vars = pca.fit_transform(standard_scaled_vars)

In [76]:
np.sum(pca.explained_variance_ratio_)

np.float64(0.41397169972177283)